---

- hosts: localhost
  connection: local

  tasks:
    - name: install python2-dnf
      command: dnf install -y python2-dnf
      args:
        creates: /usr/bin/dnf-2
      become: yes

    - name: add docker yum repo
      yum_repository:
          name: docker
          description: Docker Official YUM Repository
          baseurl: http://yum.dockerproject.org/repo/main/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}
          enabled: yes
          gpgkey: http://yum.dockerproject.org/gpg

    - name: update all packages
      dnf:
          name: "*"
          state: latest
      become: yes

    - name: install packages
      dnf: name={{ item }} state=latest
      with_items:
      - tmux
      - git
      - vim-enhanced
      - python2-virtualenv
      - vagrant
      - hexchat
      - vagrant-libvirt
      - transmission-gtk
      - virt-manager
      - docker-engine
      become: yes

    - name: print a variable
      debug: var=ansible_user_dir
      become: no

    - name: setup virtualenv
      pip: name={{ item }} virtualenv={{ ansible_user_dir }}/venv state=latest
      with_items:
      - ipython
      - cm_api 
      become: no
